
--------------------CÂU 3------------------------

------3.1. Một sinh viên chỉ được tham gia một đề tài------
CREATE TRIGGER MOI_1_SV_1_DT ON SV_DETAI FOR INSERT, UPDATE
AS
BEGIN
DECLARE @SV INT
SELECT @SV = (SELECT COUNT(MSSV) FROM SV_DETAI WHERE
MSSV = (SELECT MSSV FROM INSERTED))
IF (@SV <> 1)
	BEGIN
		PRINT 'MOI SV CHI DUOC THAM GIA 1 DE TAI'
		ROLLBACK TRANSACTION
	END
END


------3.2. Một đề tài không có quá 3 sinh viên tham gia------
CREATE TRIGGER MOI_1_DT_KHONGQUA_3_SV ON SV_DETAI FOR INSERT, UPDATE
AS
BEGIN
DECLARE @DT INT
SELECT @DT = (SELECT COUNT(MSDT) FROM SV_DETAI WHERE
MSDT = (SELECT MSDT FROM INSERTED))
IF (@DT > 3)
	BEGIN
		PRINT 'DT TOI DA 3 SV THAM GIA'
		ROLLBACK TRANSACTION

	END
END


------3.3. Điểm của đề tài trong thang điểm từ 0 đến 10------
CREATE TRIGGER DIEM_GV_HDDT ON GV_HDDT FOR INSERT,UPDATE
AS
BEGIN
DECLARE @DIEM FLOAT
SELECT @DIEM = (SELECT DIEM FROM GV_HDDT WHERE MSDT = (SELECT MSDT FROM INSERTED))
IF (@DIEM < 0 OR @DIEM > 10)
	BEGIN
		PRINT 'DIEM KHONG PHU HOP'
		ROLLBACK TRANSACTION
	END
END


CREATE TRIGGER DIEM_GV_PBDT ON GV_PBDT FOR INSERT, UPDATE
AS
BEGIN
DECLARE @DIEM FLOAT
SELECT @DIEM = (SELECT DIEM FROM GV_PBDT WHERE MSDT = (SELECT MSDT FROM INSERTED))
IF (@DIEM < 0 OR @DIEM > 10)
	BEGIN
		PRINT 'DIEM KHONG PHU HOP'
		ROLLBACK TRANSACTION
	END
END

CREATE TRIGGER DIEM_GV_UVDT ON GV_UVDT FOR INSERT,UPDATE
AS
BEGIN
DECLARE @DIEM FLOAT
SELECT @DIEM = (SELECT DIEM FROM GV_UVDT WHERE MSDT = (SELECT MSDT FROM INSERTED))
IF (@DIEM < 0 OR @DIEM > 10)
	BEGIN
		PRINT 'DIEM KHONG PHU HOP'
		ROLLBACK TRANSACTION
	END
END



------3.4. GV là chủ tịch hội đồng phải có học vị tiến sĩ------
CREATE TRIGGER CHU_TICH_HD_1 ON HOCVI FOR UPDATE
AS
BEGIN
IF (N'Tiến sĩ' IN (SELECT TENHV FROM DELETED))
	BEGIN
		PRINT 'CHU TICH HOI DONG PHAI LA TIEN SI'
		ROLLBACK TRANSACTION
	END
END


CREATE TRIGGER CHU_TICH_HD_2 ON HOIDONG FOR INSERT,UPDATE
AS
BEGIN
DECLARE @A INT
SET @A = (SELECT MSGV FROM INSERTED)
IF (N'Tiến sĩ' NOT IN (SELECT TENHV FROM HOCVI WHERE MSHV =
	(SELECT MSHV FROM GV_HV_CN WHERE MSGV = @A)))
	BEGIN
		PRINT 'CHU TICH HOI DONG PHAI LA TIEN SI'
		ROLLBACK TRANSACTION
	END
END


CREATE TRIGGER CHU_TICH_HD_3 ON GV_HV_CN FOR DELETE
AS
BEGIN
DECLARE @A INT, @B INT
SET @A = (SELECT MSGV FROM DELETED)
SET @B = (SELECT MSHV FROM DELETED)
IF (N'Tiến sĩ' IN (SELECT TENHV FROM HOCVI WHERE MSHV=@B)
AND @A IN (SELECT MSGV FROM HOIDONG))
	BEGIN
		PRINT 'CHU TICH HOI DONG PHAI LA TIEN SI'
		ROLLBACK TRANSACTION
	END
END


CREATE TRIGGER CHU_TICH_HD_4 ON GV_HV_CN FOR UPDATE
AS
BEGIN
DECLARE @A INT, @B INT
SET @A = (SELECT MSGV FROM DELETED)
SET @B = (SELECT MSHV FROM DELETED)
IF (N'Tiến sĩ' IN (SELECT TENHV FROM HOCVI WHERE MSHV=@B)
AND @A IN (SELECT MSGV FROM HOIDONG))
	BEGIN
		IF (@A != (SELECT MSGV FROM INSERTED) OR @B !=
		(SELECT MSHV FROM INSERTED))

			BEGIN
				PRINT 'CHU TICH HOI DONG PHAI LA TIEN SI'
				ROLLBACK TRANSACTION
			END

	END
END






--------------------CÂU 4------------------------

------4.1. Tìm điểm trung bình của một đề tài------
CREATE FUNCTION DIEM_TB(@MSDT CHAR(6)) RETURNS FLOAT
AS
BEGIN
DECLARE @A FLOAT, @B FLOAT, @C FLOAT
IF ( EXISTS (SELECT * FROM GV_HDDT WHERE MSDT=@MSDT))
	SET @A = (SELECT AVG(DIEM) FROM GV_HDDT WHERE MSDT=@MSDT)
ELSE
	SET @A = 0
IF ( EXISTS (SELECT * FROM GV_PBDT WHERE MSDT=@MSDT))
	SET @B = (SELECT AVG(DIEM) FROM GV_PBDT WHERE MSDT=@MSDT)
ELSE
	SET @B = 0
IF ( EXISTS (SELECT * FROM GV_UVDT WHERE MSDT=@MSDT))
	SET @C = (SELECT AVG(DIEM) FROM GV_UVDT WHERE MSDT=@MSDT)
ELSE
	SET @C = 0
RETURN (@A+@B+@C)/3
END



------4.2. In ra danh sách điểm trung bình của mỗi đề tài trong danh sách đề tài------

CREATE FUNCTION DS_DIEM_TB_DETAI() RETURNS @DS TABLE(MSDT
CHAR(6),TENDT NVARCHAR(30), DIEM_TB FLOAT)
AS
BEGIN
INSERT INTO @DS
SELECT DETAI.MSDT, DETAI.TENDT, dbo.DIEM_TB_DETAI(DETAI.MSDT) FROM DETAI
RETURN
END



------4.3. In ra danh sách giảng viên có phản biện đề tài------

CREATE PROCEDURE DS_GV_PBDT
AS
BEGIN
SELECT DISTINCT GV.MSGV, GV.TENGV
FROM GIAOVIEN GV JOIN GV_PBDT PB ON GV.MSGV = PB.MSGV
END


------4.4. In ra danh sách các đề tài trong một hội đồng------

CREATE PROCEDURE DS_GV_HDDT
AS
BEGIN
SELECT DISTINCT DT.MSDT, DT.TENDT
FROM DETAI DT JOIN GV_HDDT HD ON DT.MSDT = HD.MSDT
END



--------------------CÂU 5------------------------

------5.1------

CREATE LOGIN GIANGVIEN WITH PASSWORD = '123'
CREATE USER GIANGVIEN FOR LOGIN GIANGVIEN

CREATE LOGIN GIAOVU WITH PASSWORD = '123'
CREATE USER GIAOVU FOR LOGIN GIAOVU

CREATE LOGIN SINHVIEN WITH PASSWORD = '123'
CREATE USER SINHVIEN FOR LOGIN SINHVIEN

------5.2------

----GIAOVU có quyền xem và chỉnh sửa trên tất cả các bảng----

EXEC sp_addrolemember 'db_datareader', 'GIAOVU'
EXEC sp_addrolemember 'db_datawriter', 'GIAOVU'

----GIANGVIEN có quyền xem trên các bảng liên quan đến thông tin giáo viên,.....----

GRANT SELECT ON GIAOVIEN TO GIANGVIEN
GRANT SELECT ON GV_HV_CN TO GIANGVIEN
GRANT SELECT ON SINHVIEN TO GIANGVIEN
GRANT SELECT ON SV_DETAI TO GIANGVIEN
GRANT SELECT ON GV_HDDT TO GIANGVIEN
GRANT SELECT ON GV_PBDT TO GIANGVIEN
GRANT SELECT ON GV_UVDT TO GIANGVIEN
GRANT SELECT ON HOIDONG TO GIANGVIEN
GRANT SELECT ON HOIDONG_GV TO GIANGVIEN
GRANT SELECT ON HOIDONG_DT TO GIANGVIEN
GRANT UPDATE ON GIAOVIEN TO GIANGVIEN
GRANT UPDATE ON GV_HV_CN TO GIANGVIEN

----SINHVIEN có quyền xem thông tin của sinh viên, của hội đồng và các đề tài hiện hữu trên hệ thống----

GRANT SELECT ON SINHVIEN TO SINHVIEN
GRANT SELECT ON SV_DETAI TO SINHVIEN
GRANT SELECT ON HOIDONG TO SINHVIEN
GRANT SELECT ON DETAI TO SINHVIEN

----Tất cả người dùng đều ko có quyền xóa thông tin----
DENY DELETE ON CHUYENNGANH TO GIAOVU
DENY DELETE ON DETAI TO GIAOVU
DENY DELETE ON GV_HDDT TO GIAOVU
DENY DELETE ON GV_HV_CN TO GIAOVU
DENY DELETE ON GV_PBDT TO GIAOVU
DENY DELETE ON GV_UVDT TO GIAOVU
DENY DELETE ON GIAOVIEN TO GIAOVU
DENY DELETE ON HOCVI TO GIAOVU
DENY DELETE ON HOCHAM TO GIAOVU
DENY DELETE ON HOIDONG TO GIAOVU
DENY DELETE ON HOIDONG_DT TO GIAOVU
DENY DELETE ON HOIDONG_GV TO GIAOVU
DENY DELETE ON SINHVIEN TO GIAOVU
DENY DELETE ON SV_DETAI TO GIAOVU


DENY DELETE ON CHUYENNGANH TO GIANGVIEN
DENY DELETE ON DETAI TO GIANGVIEN
DENY DELETE ON GV_HDDT TO GIANGVIEN
DENY DELETE ON GV_HV_CN TO GIANGVIEN
DENY DELETE ON GV_PBDT TO GIANGVIEN
DENY DELETE ON GV_UVDT TO GIANGVIEN
DENY DELETE ON GIAOVIEN TO GIANGVIEN
DENY DELETE ON HOCVI TO GIANGVIEN
DENY DELETE ON HOCHAM TO GIANGVIEN
DENY DELETE ON HOIDONG TO GIANGVIEN
DENY DELETE ON HOIDONG_DT TO GIANGVIEN
DENY DELETE ON HOIDONG_GV TO GIANGVIEN
DENY DELETE ON SINHVIEN TO GIANGVIEN
DENY DELETE ON SV_DETAI TO GIANGVIEN


DENY DELETE ON CHUYENNGANH TO SINHVIEN
DENY DELETE ON DETAI TO SINHVIEN
DENY DELETE ON GV_HDDT TO SINHVIEN
DENY DELETE ON GV_HV_CN TO SINHVIEN
DENY DELETE ON GV_PBDT TO SINHVIEN
DENY DELETE ON GV_UVDT TO SINHVIEN
DENY DELETE ON GIAOVIEN TO SINHVIEN
DENY DELETE ON HOCVI TO SINHVIEN
DENY DELETE ON HOCHAM TO SINHVIEN
DENY DELETE ON HOIDONG TO SINHVIEN
DENY DELETE ON HOIDONG_DT TO SINHVIEN
DENY DELETE ON HOIDONG_GV TO SINHVIEN
DENY DELETE ON SINHVIEN TO SINHVIEN
DENY DELETE ON SV_DETAI TO SINHVIEN



--------------------CÂU 6------------------------
-----a) Thông tin GV phản biện------

CREATE VIEW DANHSACH_GVPB
AS
SELECT DISTINCT GV.MSGV, TENGV, TENHV, TENHH, SODT, DIACHI
FROM GIAOVIEN GV, HOCHAM HH, HOCVI HV, GV_PBDT, 
	(
		SELECT MSGV, MAX(MSHV) MSHV
		FROM GV_HV_CN
		GROUP BY MSGV
	) AS TEMP
WHERE GV.MSGV = GV_PBDT.MSGV
	AND GV.MSHH = HH.MSHH
	AND GV.MSGV = TEMP.MSGV
	AND TEMP.MSHV = HV.MSHV


SELECT * FROM DANHSACH_GVPB


-----b) Thông tin hội đồng chấm đề tài

CREATE VIEW HOIDONG_CHAM_DETAI 
AS
SELECT D.TENDT,HD.MSHD,H.PHONG,H.NGAYHD,H.TGBD,G.TENGV
FROM DETAI D, HOIDONG H,HOIDONG_DT HD, GIAOVIEN G
WHERE D.MSDT=HD.MSDT AND H.MSHD=HD.MSHD AND H.MSGV=G.MSGV

SELECT * FROM HOIDONG_CHAM_DETAI



-----c) Thông tin điểm đề tài (lưu ý: điểm làm tròn 2 chữ số)-----

CREATE FUNCTION DIEMTBA (@MSDT CHAR(6))
RETURNS DECIMAL(4,2)
AS
BEGIN
	DECLARE @D1 FLOAT, @D2 FLOAT, @D3 FLOAT, @DEM TINYINT, @DTB
DECIMAL(4,2)
	SET @D1=0
	SET @D2=0
	SET @D3=0
	SET @DEM=0
	SET @DTB=0

	IF EXISTS ( SELECT * FROM GV_HDDT WHERE GV_HDDT.MSDT=@MSDT)
	SELECT @D1=SUM(A.DIEM), @DEM+=COUNT(*)
	FROM GV_HDDT A
	 WHERE A.MSDT=@MSDT

	IF EXISTS ( SELECT * FROM GV_PBDT WHERE GV_PBDT.MSDT=@MSDT)
	SELECT @D2=SUM(B.DIEM),@DEM+= COUNT(*)
	FROM GV_PBDT B
	WHERE B.MSDT=@MSDT

	IF EXISTS ( SELECT * FROM GV_UVDT WHERE MSDT=@MSDT)
	SELECT @D3=SUM(C.DIEM),@DEM+=COUNT(*)
	FROM GV_UVDT C
	WHERE C.MSDT=@MSDT
	IF @DEM=0
		SET @DTB=0
	ELSE
		SET @DTB=(@D1+@D2+@D3)/(@DEM)
	RETURN @DTB
END

CREATE VIEW THONGTIN_DIEM AS
	SELECT DISTINCT HOIDONG_DT.MSDT, TENDT, MSHD,
QUYETDINH,dbo.DIEMTBA(HOIDONG_DT.MSDT) AS DIEMTRUNGBINH
	FROM DETAI JOIN HOIDONG_DT ON DETAI.MSDT=HOIDONG_DT.MSDT


